name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            arch: x64
          - os: macos
            arch: x64
          - os: macos
            arch: arm64
          - os: linux
            arch: x64
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: MAA_YYS_FULL_${{ matrix.os }}-${{ matrix.arch }}.*
          mirrorchyan_rid: MaaYYs

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: TanyaShue
          repo: MaaYYs
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

  # 兼容老版本升级
  mirrorchyan_res:
    runs-on: macos-latest
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "MAA_YYS_FULL_windows-x64.zip"
          mirrorchyan_rid: MaaYYs

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: TanyaShue
          repo: MaaYYs
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
